OrdererOrgs:
    - Name: Orderer
      Domain: my.sample
      Specs:
          - Hostname: orderer

PeerOrgs:
    - Name: Org1
      Domain: org1.my.sample
      Template:
          Count: 1
      Users:
          Count: 1

    - Name: Org2
      Domain: org2.my.sample
      Template:
          Count: 1
      Users:
          Count: 1

    - Name: Org3
      Domain: org3.my.sample
      Template:
          Count: 1
      Users:
          Count: 1

    - Name: Org4
      Domain: org4.my.sample
      Template:
          Count: 1
      Users:
          Count: 1
